apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxphpupload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxphpupload
  template:
    metadata:
      labels:
        app: nginxphpupload
    spec:
      containers:
      - name: nginxphpupload
        image: idjohnson/nginxphpupload:0.0.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: upload-volume
          mountPath: /var/www/html/uploads
      volumes:
      - name: upload-volume
        persistentVolumeClaim:
          claimName: upload-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginxphpupload-service
spec:
  selector:
    app: nginxphpupload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

